import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, SignedOut, SignedIn, SignIn, SignUp, UserButton } from '@clerk/nextjs'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* agar user sigend out he to SignIn/SignUp dikhao */}
        <div className="flex items-center justify-center min-h-screen">
          <SignedOut>
            <SignIn />
          </SignedOut>
        </div>
        {/* or agar user Sigend In he to hamre childeren ko render krdo */}
        <SignedIn>
          <header className="fixed top-0 right-0 p-4 z-50">
            <UserButton />
          </header>
          {children}
        </SignedIn>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
